"""Crear tabla eventos

Revision ID: 891fa679542b
Revises: 
Create Date: 2026-04-06 12:50:11.436621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891fa679542b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('creado', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actualizado', sa.DateTime(), nullable=True))
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('url_twitch',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_column('creado_en')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DATETIME(), nullable=True))
        batch_op.alter_column('url_twitch',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('actualizado')
        batch_op.drop_column('creado')
        batch_op.drop_column('contenido')

    # ### end Alembic commands ###
